[package]
name = "retriever"
version = "0.0.1"
authors = ["Christopher Lane Hinson <clanehin@gmail.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
fnv = { version = "1.0.6", optional = true }
log = { version = "0.4", optional = true }

[dev-dependencies]
criterion = "0.3"
simple_logger = "1.3.0"

[features]
use_fnv = ["fnv"]
use_log = ["log"]

[[bench]]
name = "basic"
harness = false
